### ISSUE TITLE
To-Do List and First Meeting Information

### ISSUE THREAD

**Issue by quantum-satire** [Pomilui/Akira_Page#1]
**Meetings:** _every Monday_ from _11:30 - 1_ in _FOB 131_

We have decided to switch focus from examining the Manga to examining the Anime adaptation of _Akira_ for the project.

---

### Anime
- Control ✔
- Metamorphosis
- Military-Industrial Complex
- Psychological Aspect(s) ✔
- Oppression and Repression ✔
- Cultural Influence (The A-Bomb)
- Changes in Scripts (Between Anime and Manga OR versions of Anime)
- Artwork

### How to Interpret With Markup
- Word Choice and Inflection

### Things To Do Before Next Meeting:

- [x] Aquire a copy of the anime for viewing
- [x] Aquire an accurate script and push to the repo
- [ ] Practice pushing, pulling, and notifying each other with GitHub
- [x] [_Explore other projects for ideas_](http://dh.newtfire.org/studentProjects.html)

@Pomilui @MarkTheShark01

**Comment by ebeshero** [comment]
Hey team! Have you added me (@ebeshero) and @jonhoranic as collaborators on your repo?

**Comment by Pomilui** [comment]
Yep.

________________________________

**Comment by ebeshero** [comment]
Got it! Nearly missed it in the avalanche of email today... 👍

**Comment by quantum-satire** [comment]
@Pomilui @MarkTheShark01 Because the IT interviews are this coming week, do we want to meet on Tuesday instead of Monday for this week only? I'm meeting with Dorothea on Thursday, so I will not be able to meet then unless you two want to meet without me. I know we wanted to watch the movie as a group, so we will also need an accurate script for the version of the movie we are watching as well as maybe two hours of time for this meeting. What are you guys thinking as far as meeting times this week?

**Comment by Pomilui** [comment]
@quantum-satire @MarkTheShark01  

I can always come in early on Monday, or I'm free Monday from 1-2, 3-4 and after 5:15.  On Tuesday, I'm pretty sure that I'm free from 10-12:30 and after 2:15.  What are your Tuesdays and Wed. like, Mark?

 - Nick

**Comment by quantum-satire** [comment]
@Pomilui I have a class from 9 - 10:20, so I won't be able to come in early tomorrow :( 
I work until 4 tomorrow and can meet any time after then.
I tutor on Tuesday from 12 - 1, so I can meet before then, or after 3:45.

**Comment by Pomilui** [comment]
My last class tomorrow ends at 5:15.  We can shoot for then, Tuesday morning from 10-12 or Tuesday after 3:45.  Gotta see how Mark's schedule fits in, too.  I think I'll shoot him an email.
