### ISSUE TITLE
To-Do List and Meeting Notes [2018-02-05]

### ISSUE THREAD

**Issue by quantum-satire** [Pomilui/Akira_Page#3]
### To Do by next Monday's Meeting [2018-02-012]
- [x] Mark up the script with some (tentative) Regex
    - This means thinking about the script, then converting it into valid XML
    - What do we want to mark and enclose?
- [ ] Brainstorm some ideas for where you want to take this project
    - [**_Look at some other projects for ideas_**](http://dh.newtfire.org/studentProjects.html)
- [ ] Write some background information on:
    - Timeline (pre- and post- movie)
    - Evens that happen during the movie
    - Characters and their purpose in the movie
    - The culture of "Neo-Tokyo" and the 80s influence

Shout out for help with an @ tag!

**Comment by Pomilui** [comment]
@quantum-satire  @MarkTheShark01  Some stuff done.  Going to push some files for tomorrow.
